// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project7_wmbRESTApi.Database.DataBases;

#nullable disable

namespace Project7wmbRESTApi.Database.Migrations
{
    [DbContext(typeof(WarungContext))]
    partial class WarungContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("IsPayment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TableId")
                        .HasColumnType("integer");

                    b.Property<string>("TransTypeId")
                        .IsRequired()
                        .HasColumnType("VarChar(3)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.HasIndex("TransTypeId");

                    b.ToTable("t_bill", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.BillDetail", b =>
                {
                    b.Property<int>("BillDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillDetailId"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuPriceId")
                        .HasColumnType("integer");

                    b.Property<float>("Qty")
                        .HasColumnType("Float4");

                    b.HasKey("BillDetailId");

                    b.HasIndex("BillId");

                    b.HasIndex("MenuPriceId");

                    b.ToTable("t_bill_detail", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("VarChar(50)");

                    b.Property<bool?>("IsMember")
                        .HasColumnType("boolean");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("VarChar(20)");

                    b.HasKey("CustomerId");

                    b.ToTable("m_customer", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.CustomerDiscount", b =>
                {
                    b.Property<int>("CustDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustDiscountId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("integer");

                    b.HasKey("CustDiscountId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DiscountId");

                    b.ToTable("m_customer_discount", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiscountId"));

                    b.Property<string>("DiscDesciption")
                        .HasColumnType("VarChar(50)");

                    b.Property<int?>("Percent")
                        .HasColumnType("integer");

                    b.HasKey("DiscountId");

                    b.ToTable("m_discount", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<string>("MenuCode")
                        .IsRequired()
                        .HasColumnType("VarChar(5)");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("VarChar(100)");

                    b.HasKey("MenuId");

                    b.ToTable("m_menu", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.MenuPrice", b =>
                {
                    b.Property<int>("MenuPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuPriceId"));

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<float>("Price")
                        .HasColumnType("Float4");

                    b.HasKey("MenuPriceId");

                    b.HasIndex("MenuId");

                    b.ToTable("m_menu_price", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TableId"));

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("VarChar(3)");

                    b.HasKey("TableId");

                    b.ToTable("m_table", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.TransType", b =>
                {
                    b.Property<string>("TransTypeId")
                        .HasColumnType("VarChar(3)");

                    b.Property<string>("Description")
                        .HasColumnType("VarChar(50)");

                    b.HasKey("TransTypeId");

                    b.ToTable("m_trans_type", "dbo");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Bill", b =>
                {
                    b.HasOne("Project7_wmbRESTApi.Database.Models.Customer", "Customers")
                        .WithMany("Bills")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project7_wmbRESTApi.Database.Models.Table", "Tables")
                        .WithMany("Bills")
                        .HasForeignKey("TableId");

                    b.HasOne("Project7_wmbRESTApi.Database.Models.TransType", "TransTypes")
                        .WithMany("Bills")
                        .HasForeignKey("TransTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customers");

                    b.Navigation("Tables");

                    b.Navigation("TransTypes");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.BillDetail", b =>
                {
                    b.HasOne("Project7_wmbRESTApi.Database.Models.Bill", "Bills")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project7_wmbRESTApi.Database.Models.MenuPrice", "MenuPrices")
                        .WithMany("BillDetails")
                        .HasForeignKey("MenuPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bills");

                    b.Navigation("MenuPrices");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.CustomerDiscount", b =>
                {
                    b.HasOne("Project7_wmbRESTApi.Database.Models.Customer", "Customers")
                        .WithMany("CustomerDiscounts")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Project7_wmbRESTApi.Database.Models.Discount", "Discounts")
                        .WithMany("CustomerDiscounts")
                        .HasForeignKey("DiscountId");

                    b.Navigation("Customers");

                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.MenuPrice", b =>
                {
                    b.HasOne("Project7_wmbRESTApi.Database.Models.Menu", "Menus")
                        .WithMany("MenuPrices")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Customer", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("CustomerDiscounts");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Discount", b =>
                {
                    b.Navigation("CustomerDiscounts");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Menu", b =>
                {
                    b.Navigation("MenuPrices");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.MenuPrice", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.Table", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Project7_wmbRESTApi.Database.Models.TransType", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
